import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Our Sweet Comma",
  description: "Generated by IB 4th Siu, Yewon, Minsol",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 w-full h-16 bg-var(--background) z-50 p-4">
          <div className="relative flex items-center w-full px-4">
            <nav className="absolute left-1/2 top-1/2 transform -translate-x-1/2 flex space-x-20">
              <a href="/" className="w-24 h-11 rounded-[40px] border-2 border-var(--foreground) flex items-center justify-center text-lg">Home</a>
              <a href="/cas" className="w-24 h-11 rounded-[40px] border-2 border-var(--foreground) flex items-center justify-center text-lg">Cas</a>
              <a href="/about" className="w-24 h-11 rounded-[40px] border-2 border-var(--foreground) flex items-center justify-center text-lg">About</a>
            </nav>
          </div>
        </header>
        <main className="mt-18">
        {children}
        </main>
      </body>
    </html>
  );
}
