import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bad_Script } from "next/font/google";
import Header from "./_components/header";
import { Suspense } from "react";

const badScript = Bad_Script({
  variable: "--font-bad-script",
  subsets: ["latin"],
  weight: "400"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Our Sweet Comma",
  description: "Generated by IB 4th Siu, Yewon, Minsol",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${badScript.variable}`}>
      <body className={'flex  antialiased h-screen w-screen overflow-x-hidden'}>
        <Suspense>
          <Header />
        </Suspense>
        <main className="static flex-col justify-center items-center w-screen h-full overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}